
name: build-angle

on:
  workflow_dispatch:
      branches:
      - main

jobs:
  info:
    runs-on: ubuntu-24.04
    outputs:
      ANGLE_COMMIT: ${{ steps.info.outputs.ANGLE_COMMIT }}
      BUILD_DATE: ${{ steps.info.outputs.BUILD_DATE }}
    steps:
      - name: Get Latest Commit Id
        id: info
        run: |
          echo ANGLE_COMMIT=`git ls-remote https://chromium.googlesource.com/angle/angle HEAD | awk '{ print $1 }'` >> ${GITHUB_OUTPUT}
          echo BUILD_DATE=`date +'%Y-%m-%d'` >> ${GITHUB_OUTPUT}

  build:
    runs-on: windows-2022
    needs: info
    strategy:
      matrix:
        arch: [x86, arm]
    env:
      ANGLE_COMMIT: ${{ needs.info.outputs.ANGLE_COMMIT }}
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      #- name: Install Windows SDK v10.0.26100.0
      #  shell: cmd
      #  run: |
      #    "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet --force --norestart --add Microsoft.VisualStudio.Component.Windows11SDK.26100


      - name: Install Dependencies
        run: |
          git clone https://chromium.googlesource.com/angle/angle
          cd angle
          git checkout ${{ env.ANGLE_COMMIT }}
          python scripts/bootstrap.py
          python scripts/run_vs2019.py

      - name: Configure Build for Static Library
        run: |
          cd angle
          gn gen out/Static-${{ matrix.arch }} --args="is_debug=false target_cpu='${{ matrix.arch }}' angle_enable_static=true"

      - name: Build ANGLE Static Library
        run: |
          cd angle
          ninja -C out/Static-${{ matrix.arch }}

      - name: Package Static Library
        run: |
          cd angle
          zip -r angle-${{ matrix.arch }}-${{ env.BUILD_DATE }}.zip out/Static-${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angle-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}
          path: angle-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}.zip
          if-no-files-found: error
          compression-level: 0

